export {LoginPage} from './login';
export {ChatsPage} from './chats';
export {EditProfilePage} from './editProfile';
export {ErrorPage} from './error';
export {NotFoundPage} from './notFound';
export {ProfilePage} from './profile';
export {RegisterPage} from './register';
export {ResetPasswordPage} from './resetPassword';
export {NavigatePage} from './navigate';
